/left_gripper/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    robotiq_gripper_controller:
      type: parallel_gripper_action_controller/GripperActionController
    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController

/left_gripper/robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: left_robotiq_85_left_knuckle_joint
    use_effort_interface: true
    use_speed_interface: true

/left_gripper/robotiq_activation_controller:
  ros__parameters:
    default: true

/left_gripper/joint_state_broadcaster:
  ros__parameters:
    extra_interfaces:
      - object_detection_status

/right_gripper/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    robotiq_gripper_controller:
      type: parallel_gripper_action_controller/GripperActionController
    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController

/right_gripper/robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: right_robotiq_85_right_knuckle_joint
    use_effort_interface: true
    use_speed_interface: true

/right_gripper/robotiq_activation_controller:
  ros__parameters:
    default: true

/right_gripper/joint_state_broadcaster:
  ros__parameters:
    extra_interfaces:
      - object_detection_status